2025-03-05 14:59:57,054 - messaging - INFO - performance_logger.py:20 - LATENCY: rabbitmq_connection took 80.26ms
2025-03-05 14:59:57,056 - messaging - INFO - subscriber.py:81 - Successfully connected to RabbitMQ
2025-03-05 14:59:57,067 - messaging - INFO - subscriber.py:121 - Started consuming messages from RabbitMQ
2025-03-05 15:00:02,194 - messaging - INFO - subscriber.py:97 - Received move: {'from_square': 'g8', 'to_square': 'h6', 'message_id': '22b671ba', 'timestamp': 1741186802.1919882}
2025-03-05 15:00:02,195 - messaging - INFO - performance_logger.py:20 - LATENCY: message_delivery took 3.59ms
2025-03-05 15:00:02,199 - messaging - INFO - subscriber.py:97 - Received move: {'from_square': 'f7', 'to_square': 'f5', 'message_id': '43e94bb3', 'timestamp': 1741186802.1934998}
2025-03-05 15:00:02,199 - messaging - INFO - performance_logger.py:20 - LATENCY: message_delivery took 6.05ms
2025-03-05 15:00:05,301 - messaging - INFO - performance_logger.py:31 - MOVE: g8h6 FAILURE (planning: 0.00ms, execution: 3034.62ms)
2025-03-05 15:00:05,301 - messaging - ERROR - performance_logger.py:35 - ERROR: movement - execution_failure: Move g8h6
2025-03-05 15:00:07,644 - messaging - INFO - performance_logger.py:31 - MOVE: f7f5 FAILURE (planning: 0.00ms, execution: 2241.98ms)
2025-03-05 15:00:07,647 - messaging - ERROR - performance_logger.py:35 - ERROR: movement - execution_failure: Move f7f5
2025-03-05 15:00:27,002 - messaging - INFO - subscriber.py:184 - RabbitMQ connection closed
